INSERT INTO public.sys_menu (id, menu_type, menu_name, icon_type, icon, route_name, route_path, component, path_param, status, active_menu, hide_in_menu, pid, sequence, i18n_key, keep_alive, constant, href, multi_tab, created_at, created_by, updated_at, updated_by) VALUES (1, 'menu', 'login', 1, null, 'login', '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?', 'layout.blank$view.login', null, 'ENABLED', null, true, 0, 0, 'route.login', false, true, null, false, '2024-05-15 00:00:00.000', '-1', null, null);
INSERT INTO public.sys_menu (id, menu_type, menu_name, icon_type, icon, route_name, route_path, component, path_param, status, active_menu, hide_in_menu, pid, sequence, i18n_key, keep_alive, constant, href, multi_tab, created_at, created_by, updated_at, updated_by) VALUES (2, 'menu', '403', 1, null, '403', '/403', 'layout.blank$view.403', null, 'ENABLED', null, true, 0, 0, 'route.403', false, true, null, false, '2024-05-15 00:00:00.000', '-1', null, null);
INSERT INTO public.sys_menu (id, menu_type, menu_name, icon_type, icon, route_name, route_path, component, path_param, status, active_menu, hide_in_menu, pid, sequence, i18n_key, keep_alive, constant, href, multi_tab, created_at, created_by, updated_at, updated_by) VALUES (3, 'menu', '404', 1, null, '404', '/404', 'layout.blank$view.404', null, 'ENABLED', null, true, 0, 0, 'route.404', false, true, null, false, '2024-05-15 00:00:00.000', '-1', null, null);
INSERT INTO public.sys_menu (id, menu_type, menu_name, icon_type, icon, route_name, route_path, component, path_param, status, active_menu, hide_in_menu, pid, sequence, i18n_key, keep_alive, constant, href, multi_tab, created_at, created_by, updated_at, updated_by) VALUES (4, 'menu', '500', 1, null, '500', '/500', 'layout.blank$view.500', null, 'ENABLED', null, true, 0, 0, 'route.500', false, true, null, false, '2024-05-15 00:00:00.000', '-1', null, null);
INSERT INTO public.sys_menu (id, menu_type, menu_name, icon_type, icon, route_name, route_path, component, path_param, status, active_menu, hide_in_menu, pid, sequence, i18n_key, keep_alive, constant, href, multi_tab, created_at, created_by, updated_at, updated_by) VALUES (5, 'menu', 'iframe-page', 1, null, 'iframe-page', '/iframe-page/:url', 'layout.base$view.iframe-page', null, 'ENABLED', null, true, 0, 0, 'route.iframe-page', false, true, null, false, '2024-05-15 00:00:00.000', '-1', null, null);
INSERT INTO public.sys_menu (id, menu_type, menu_name, icon_type, icon, route_name, route_path, component, path_param, status, active_menu, hide_in_menu, pid, sequence, i18n_key, keep_alive, constant, href, multi_tab, created_at, created_by, updated_at, updated_by) VALUES (62, 'menu', 'manage_menu', 1, 'material-symbols:route', 'manage_menu', '/manage/menu', 'view.manage_menu', null, 'ENABLED', null, false, 54, 2, 'route.manage_menu', true, false, null, false, '2024-05-15 00:00:00.000', '-1', null, null);
INSERT INTO public.sys_menu (id, menu_type, menu_name, icon_type, icon, route_name, route_path, component, path_param, status, active_menu, hide_in_menu, pid, sequence, i18n_key, keep_alive, constant, href, multi_tab, created_at, created_by, updated_at, updated_by) VALUES (65, 'menu', 'manage_user-detail', 1, null, 'manage_user-detail', '/manage/user-detail/:id', 'view.manage_user-detail', null, 'ENABLED', 'manage_user', true, 54, 3, 'route.manage_user-detail', false, false, null, false, '2024-05-15 00:00:00.000', '-1', null, null);
INSERT INTO public.sys_menu (id, menu_type, menu_name, icon_type, icon, route_name, route_path, component, path_param, status, active_menu, hide_in_menu, pid, sequence, i18n_key, keep_alive, constant, href, multi_tab, created_at, created_by, updated_at, updated_by) VALUES (50, 'menu', 'home', 1, 'mdi:monitor-dashboard', 'home', '/home', 'layout.base$view.home', null, 'ENABLED', null, false, 0, 0, 'route.home', false, false, null, false, '2024-05-15 00:00:00.000', '-1', null, null);
INSERT INTO public.sys_menu (id, menu_type, menu_name, icon_type, icon, route_name, route_path, component, path_param, status, active_menu, hide_in_menu, pid, sequence, i18n_key, keep_alive, constant, href, multi_tab, created_at, created_by, updated_at, updated_by) VALUES (54, 'directory', 'manage', 1, 'carbon:cloud-service-management', 'manage', '/manage', 'layout.base', null, 'ENABLED', null, false, 0, 4, 'route.manage', false, false, null, false, '2024-05-15 00:00:00.000', '-1', null, null);
INSERT INTO public.sys_menu (id, menu_type, menu_name, icon_type, icon, route_name, route_path, component, path_param, status, active_menu, hide_in_menu, pid, sequence, i18n_key, keep_alive, constant, href, multi_tab, created_at, created_by, updated_at, updated_by) VALUES (64, 'menu', 'manage_user', 1, 'ic:round-manage-accounts', 'manage_user', '/manage/user', 'view.manage_user', null, 'ENABLED', null, false, 54, 0, 'route.manage_user', false, false, null, false, '2024-05-15 00:00:00.000', '-1', null, null);
INSERT INTO public.sys_menu (id, menu_type, menu_name, icon_type, icon, route_name, route_path, component, path_param, status, active_menu, hide_in_menu, pid, sequence, i18n_key, keep_alive, constant, href, multi_tab, created_at, created_by, updated_at, updated_by) VALUES (63, 'menu', 'manage_role', 1, 'carbon:user-role', 'manage_role', '/manage/role', 'view.manage_role', null, 'ENABLED', null, false, 54, 1, 'route.manage_role', false, false, null, false, '2024-05-15 00:00:00.000', '-1', null, null);

INSERT INTO public.sys_menu (id, menu_type, menu_name, icon_type, icon, route_name, route_path, component, path_param, status, active_menu, hide_in_menu, pid, sequence, i18n_key, keep_alive, constant, href, multi_tab, created_at, created_by, updated_at, updated_by) values (51, 'menu', 'access-key', 1, 'carbon:document-signed', 'access-key', '/access-key', 'layout.base$view.access-key', null, 'ENABLED', null, false, '0', 0, 'route.access-key', false, false, null, false, '2024-05-15 00:00:00.000', '-1', null, null);
INSERT INTO public.sys_menu (id, menu_type, menu_name, icon_type, icon, route_name, route_path, component, path_param, status, active_menu, hide_in_menu, pid, sequence, i18n_key, keep_alive, constant, href, multi_tab, created_at, created_by, updated_at, updated_by) values (52, 'directory', 'log', 1, 'carbon:cloud-logging', 'log', '/log', 'layout.base', null, 'ENABLED', null, false, '0', 0, 'route.log', false, false, null, false, '2024-05-15 00:00:00.000', '-1', null, null);
INSERT INTO public.sys_menu (id, menu_type, menu_name, icon_type, icon, route_name, route_path, component, path_param, status, active_menu, hide_in_menu, pid, sequence, i18n_key, keep_alive, constant, href, multi_tab, created_at, created_by, updated_at, updated_by) values (71, 'menu', 'log_login', 1, 'carbon:login', 'log_login', '/log/login', 'view.log_login', null, 'ENABLED', null, false, '52', 0, 'route.log_login', false, false, null, false, '2024-05-15 00:00:00.000', '-1', null, null);
INSERT INTO public.sys_menu (id, menu_type, menu_name, icon_type, icon, route_name, route_path, component, path_param, status, active_menu, hide_in_menu, pid, sequence, i18n_key, keep_alive, constant, href, multi_tab, created_at, created_by, updated_at, updated_by) values (72, 'menu', 'log_operation', 1, 'carbon:operations-record', 'log_operation', '/log/operation', 'view.log_operation', null, 'ENABLED', null, false, '52', 0, 'route.log_operation', false, false, null, false, '2024-05-15 00:00:00.000', '-1', null, null);
