import { BadRequestException, Inject } from '@nestjs/common';
import { CommandHandler, ICommandHandler } from '@nestjs/cqrs';
import { MenuType } from '@prisma/client';

import { ROOT_ROUTE_PID } from '@lib/shared/prisma/db.constant';

import { MenuCreateCommand } from '../../commands/menu-create.command';
import { MenuReadRepoPortToken, MenuWriteRepoPortToken } from '../../constants';
import { Menu } from '../../domain/menu.model';
import { MenuCreateProperties } from '../../domain/menu.read.model';
import { MenuReadRepoPort } from '../../ports/menu.read.repo-port';
import { MenuWriteRepoPort } from '../../ports/menu.write.repo-port';
import { LowcodePageIdGenerator } from '../../services/lowcode-page-id.generator';

@CommandHandler(MenuCreateCommand)
export class MenuCreateHandler
  implements ICommandHandler<MenuCreateCommand, void>
{
  @Inject(MenuWriteRepoPortToken)
  private readonly menuWriteRepository: MenuWriteRepoPort;
  @Inject(MenuReadRepoPortToken)
  private readonly menuReadRepoPort: MenuReadRepoPort;

  private readonly lowcodePageIdGenerator = new LowcodePageIdGenerator();

  async execute(command: MenuCreateCommand) {
    // Check if routeName already exists
    const existingMenu = await this.menuReadRepoPort.getMenuByRouteName(command.routeName);
    if (existingMenu) {
      throw new BadRequestException(
        `A menu with routeName '${command.routeName}' already exists.`,
      );
    }

    if (command.pid !== ROOT_ROUTE_PID) {
      const parentMenu = await this.menuReadRepoPort.getMenuById(command.pid);

      if (!parentMenu) {
        throw new BadRequestException(
          `Parent menu with code ${command.pid} does not exist.`,
        );
      }
    }

    // 处理低代码页面ID
    // 注意：如果用户没有提供 lowcodePageId，保持为 null
    // 因为外键约束要求 lowcodePageId 必须在 sys_lowcode_page 表中存在
    // 如果需要在创建菜单时自动创建低代码页面，应该在这里先创建页面，然后使用其 ID
    let finalLowcodePageId = command.lowcodePageId;
    // 只有当用户明确提供了 lowcodePageId 时才使用，否则保持为 null
    // 如果菜单类型是 lowcode 但没有提供 lowcodePageId，可以在后续流程中创建页面
    if (command.menuType === MenuType.lowcode && !command.lowcodePageId) {
      // 对于 lowcode 类型的菜单，如果没有提供 lowcodePageId，保持为 null
      // 这样菜单可以创建成功，后续可以通过其他方式关联低代码页面
      finalLowcodePageId = null;
    }

    const menuCreateProperties: MenuCreateProperties = {
      //Tips: id is omitted as it will be auto-generated by the database
      buttons: null,
      menuName: command.menuName,
      menuType: command.menuType,
      routeName: command.routeName,
      routePath: command.routePath,
      component: command.component,
      status: command.status,
      pid: command.pid,
      order: command.order,
      constant: command.constant,
      createdAt: new Date(),
      createdBy: command.uid,
      iconType: command.iconType,
      icon: command.icon,
      pathParam: command.pathParam,
      activeMenu: command.activeMenu,
      hideInMenu: command.hideInMenu,
      i18nKey: command.i18nKey,
      keepAlive: command.keepAlive,
      href: command.href,
      multiTab: command.multiTab,
      lowcodePageId: finalLowcodePageId,
    };

    const menu = Menu.fromCreate(menuCreateProperties);
    await this.menuWriteRepository.save(menu);
  }
}
