@host = http://localhost:9528

### 登录
# @name Authentication
POST {{host}}/v1/auth/login
Content-Type: application/json

{
  "identifier": "Soybean",
  "password": "123456"
}

### 获取常量路由
GET {{host}}/v1/route/getConstantRoutes

### 获取个人信息
GET {{host}}/v1/auth/getUserInfo
Authorization: Bearer {{Authentication.response.body.data.$.token}}

### 获取用户路由
GET {{host}}/v1/authorization/getUserRoutes
Authorization: Bearer {{Authentication.response.body.data.$.token}}

############### domain start ###############
### domain 分页查询
GET {{host}}/v1/domain
Authorization: Bearer {{Authentication.response.body.data.$.token}}

### domain 新增
POST {{host}}/v1/domain
Content-Type: application/json
Authorization: Bearer {{Authentication.response.body.data.$.token}}

{
  "code": "domain-001",
  "name": "domain-001",
  "description": "domain-001"
}

### domain 更新
PUT {{host}}/v1/domain
Content-Type: application/json
Authorization: Bearer {{Authentication.response.body.data.$.token}}

{
  "id": "01J2ZTXKDTMSHMNBYH46G6YPQK",
  "code": "domain-001-1",
  "name": "domain-001-1",
  "description": "domain-001-1"
}

### domain 删除
DELETE {{host}}/v1/domain/01J4KMZTZWH81N2YSHM221BYG5
Content-Type: application/json
Authorization: Bearer {{Authentication.response.body.data.$.token}}

############### domain end ###############

############### role start ###############
### role 分页查询
GET {{host}}/v1/role
Authorization: Bearer {{Authentication.response.body.data.$.token}}

### role 新增
POST {{host}}/v1/role
Content-Type: application/json
Authorization: Bearer {{Authentication.response.body.data.$.token}}

{
  "code": "role-001",
  "name": "role-001",
  "pid": "1",
  "description": "role-001"
}

### role 更新
PUT {{host}}/v1/role
Content-Type: application/json
Authorization: Bearer {{Authentication.response.body.data.$.token}}

{
  "id": "01J2ZW92GNWNEP9SMC1VVNCCAM",
  "code": "role-001-1",
  "name": "role-001-1",
  "pid": "1",
  "description": "role-001-1"
}

### role 删除
DELETE {{host}}/v1/role/01J4KKGZGZST8V2ZK01A2G74T9
Content-Type: application/json
Authorization: Bearer {{Authentication.response.body.data.$.token}}

############### role end ###############

############### user start ###############
### user 分页查询
GET {{host}}/v1/user
Authorization: Bearer {{Authentication.response.body.data.$.token}}

### user 新增
POST {{host}}/v1/user
Content-Type: application/json
Authorization: Bearer {{Authentication.response.body.data.$.token}}

{
  "username": "johndoe",
  "password": "securePassword123",
  "domain": "example.com",
  "nickName": "John",
  "avatar": "avatar",
  "email": "john.doe@example.com",
  "phoneNumber": "123-456-7890"
}

### user 更新
PUT {{host}}/v1/user
Content-Type: application/json
Authorization: Bearer {{Authentication.response.body.data.$.token}}

{
  "id": "01J2ZVPE2B0A2DYQ7GEA5KCN2K",
  "username": "johndoe-111",
  "password": "securePassword123-111",
  "domain": "example.com-111",
  "nickName": "John-111",
  "avatar": "avatar-111",
  "email": "john.doe@example.com",
  "phoneNumber": "123-456-7890-111"
}

### user 删除
DELETE {{host}}/v1/user/01J4K9KF52CNSM079YHHXWCE1A
Content-Type: application/json
Authorization: Bearer {{Authentication.response.body.data.$.token}}

############### user end ###############

############### route start ###############

############### route end ###############

############### other start ###############
### api-endpoint 分页查询
GET {{host}}/v1/api-endpoint?size=50
Authorization: Bearer {{Authentication.response.body.data.$.token}}

### login-log 分页查询
GET {{host}}/v1/login-log
Authorization: Bearer {{Authentication.response.body.data.$.token}}

### operation-log 分页查询
GET {{host}}/v1/operation-log
Authorization: Bearer {{Authentication.response.body.data.$.token}}

############### other end ###############

############### auth start ###############
### assign-permission permission授权
POST {{host}}/v1/authorization/assign-permission
Content-Type: application/json
Authorization: Bearer {{Authentication.response.body.data.$.token}}

{
  "domain": "built-in",
  "roleId": "1",
  "permissions": ["57818da167c4d5ac712a2f6414d228ed", "51c4ec06dd17092d04af593d73d2e98f", "66da8c9bd22f9b893f4680abd920d302", "a909e26f321170c9fe4d45a7dded7e2b", "2f513bd27cae5b5b178998c38f6368b3", "2d3688801b07778813607ccbd645937e"]
}

### assign-routes route授权
POST {{host}}/v1/authorization/assign-routes
Content-Type: application/json
Authorization: Bearer {{Authentication.response.body.data.$.token}}

{
  "domain": "built-in",
  "roleId": "3",
  "routeIds": [50]
}

### assign-users user授权
POST {{host}}/v1/authorization/assign-users
Content-Type: application/json
Authorization: Bearer {{Authentication.response.body.data.$.token}}

{
  "roleId": "3",
  "userIds": ["3"]
}

### route列表
GET {{host}}/v1/route
Authorization: Bearer {{Authentication.response.body.data.$.token}}

### route 🌲
GET {{host}}/v1/route/tree
Authorization: Bearer {{Authentication.response.body.data.$.token}}

### auth-route 列举指定角色已授权路由
GET {{host}}/v1/route/auth-route/ROLE_SUPER
Content-Type: application/json
Authorization: Bearer {{Authentication.response.body.data.$.token}}

### endpoint 🌲
GET {{host}}/v1/api-endpoint/tree
Authorization: Bearer {{Authentication.response.body.data.$.token}}

### 列举指定角色已授权casbin data
GET {{host}}/v1/api-endpoint/auth-api-endpoint/ROLE_SUPER
Authorization: Bearer {{Authentication.response.body.data.$.token}}

############### auth end ###############


############### healthy start ###############
### 系统信息
GET {{host}}/v1/system-info
Authorization: Bearer {{Authentication.response.body.data.$.token}}

### redis信息
GET {{host}}/v1/redis-info
Authorization: Bearer {{Authentication.response.body.data.$.token}}

############### healthy end ###############
