/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "amis-template": () => import("@/views/_builtin/amis-template/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  reload: () => import("@/views/_builtin/reload/index.vue"),
  "access-key": () => import("@/views/access-key/index.vue"),
  "amis-demo_child1": () => import("@/views/amis-demo/child1/index.vue"),
  home: () => import("@/views/home/index.vue"),
  log_login: () => import("@/views/log/login/index.vue"),
  log_operation: () => import("@/views/log/operation/index.vue"),
  "lowcode_api-config": () => import("@/views/lowcode/api-config/index.vue"),
  "lowcode_api-test": () => import("@/views/lowcode/api-test/index.vue"),
  "lowcode_code-generation": () => import("@/views/lowcode/code-generation/index.vue"),
  "lowcode_code-generator": () => import("@/views/lowcode/code-generator/index.vue"),
  "lowcode_entity-designer": () => import("@/views/lowcode/entity-designer/index.vue"),
  lowcode_entity: () => import("@/views/lowcode/entity/index.vue"),
  lowcode_field: () => import("@/views/lowcode/field/index.vue"),
  lowcode_project: () => import("@/views/lowcode/project/[id].vue"),
  lowcode_project: () => import("@/views/lowcode/project/index.vue"),
  lowcode_query: () => import("@/views/lowcode/query/index.vue"),
  lowcode_relationship: () => import("@/views/lowcode/relationship/index.vue"),
  "lowcode_target-project": () => import("@/views/lowcode/target-project/index.vue"),
  "lowcode_template-manager": () => import("@/views/lowcode/template-manager/index.vue"),
  lowcode_template: () => import("@/views/lowcode/template/index.vue"),
  manage_menu: () => import("@/views/manage/menu/index.vue"),
  manage_role: () => import("@/views/manage/role/index.vue"),
  "manage_user-detail": () => import("@/views/manage/user-detail/[id].vue"),
  manage_user: () => import("@/views/manage/user/index.vue"),
};
