/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'amis-demo',
    path: '/amis-demo',
    component: 'layout.base',
    meta: {
      title: 'amis-demo',
      i18nKey: 'route.amis-demo'
    },
    children: [
      {
        name: 'amis-demo_child1',
        path: '/amis-demo/child1',
        component: 'view.amis-demo_child1',
        meta: {
          title: 'amis-demo_child1',
          i18nKey: 'route.amis-demo_child1',
          keepAlive: true
        }
      }
    ]
  },
  {
    name: 'amis-template',
    path: '/amis-template',
    component: 'layout.base$view.amis-template',
    meta: {
      title: 'amis-template',
      i18nKey: 'route.amis-template',
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'reload',
    path: '/reload',
    component: 'layout.base$view.reload',
    meta: {
      title: 'reload',
      i18nKey: 'route.reload'
    }
  }
];
