/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'access-key',
    path: '/access-key',
    component: 'layout.base$view.access-key',
    meta: {
      title: 'access-key',
      i18nKey: 'route.access-key'
    }
  },
  {
    name: 'amis-demo',
    path: '/amis-demo',
    component: 'layout.base',
    meta: {
      title: 'amis-demo',
      i18nKey: 'route.amis-demo'
    },
    children: [
      {
        name: 'amis-demo_child1',
        path: '/amis-demo/child1',
        component: 'view.amis-demo_child1',
        meta: {
          title: 'amis-demo_child1',
          i18nKey: 'route.amis-demo_child1',
          keepAlive: true
        }
      }
    ]
  },
  {
    name: 'amis-template',
    path: '/amis-template',
    component: 'layout.base$view.amis-template',
    meta: {
      title: 'amis-template',
      i18nKey: 'route.amis-template',
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'log',
    path: '/log',
    component: 'layout.base',
    meta: {
      title: 'log',
      i18nKey: 'route.log'
    },
    children: [
      {
        name: 'log_login',
        path: '/log/login',
        component: 'view.log_login',
        meta: {
          title: 'log_login',
          i18nKey: 'route.log_login'
        }
      },
      {
        name: 'log_operation',
        path: '/log/operation',
        component: 'view.log_operation',
        meta: {
          title: 'log_operation',
          i18nKey: 'route.log_operation'
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'lowcode',
    path: '/lowcode',
    component: 'layout.base',
    meta: {
      title: 'lowcode',
      i18nKey: 'route.lowcode'
    },
    children: [
      {
        name: 'lowcode_api-config',
        path: '/lowcode/api-config',
        component: 'view.lowcode_api-config',
        meta: {
          title: 'lowcode_api-config',
          i18nKey: 'route.lowcode_api-config'
        }
      },
      {
        name: 'lowcode_api-test',
        path: '/lowcode/api-test',
        component: 'view.lowcode_api-test',
        meta: {
          title: 'lowcode_api-test',
          i18nKey: 'route.lowcode_api-test'
        }
      },
      {
        name: 'lowcode_code-generation',
        path: '/lowcode/code-generation',
        component: 'view.lowcode_code-generation',
        meta: {
          title: 'lowcode_code-generation',
          i18nKey: 'route.lowcode_code-generation'
        }
      },
      {
        name: 'lowcode_code-generator',
        path: '/lowcode/code-generator',
        component: 'view.lowcode_code-generator',
        meta: {
          title: 'lowcode_code-generator',
          i18nKey: 'route.lowcode_code-generator'
        }
      },
      {
        name: 'lowcode_dashboard',
        path: '/lowcode/dashboard',
        component: 'view.lowcode_dashboard',
        meta: {
          title: 'lowcode_dashboard',
          i18nKey: 'route.lowcode_dashboard'
        }
      },
      {
        name: 'lowcode_entity',
        path: '/lowcode/entity',
        component: 'view.lowcode_entity',
        meta: {
          title: 'lowcode_entity',
          i18nKey: 'route.lowcode_entity'
        }
      },
      {
        name: 'lowcode_field',
        path: '/lowcode/field',
        component: 'view.lowcode_field',
        meta: {
          title: 'lowcode_field',
          i18nKey: 'route.lowcode_field'
        }
      },
      {
        name: 'lowcode_project',
        path: '/lowcode/project',
        component: 'view.lowcode_project',
        meta: {
          title: 'lowcode_project',
          i18nKey: 'route.lowcode_project'
        }
      },
      {
        name: 'lowcode_query',
        path: '/lowcode/query',
        component: 'view.lowcode_query',
        meta: {
          title: 'lowcode_query',
          i18nKey: 'route.lowcode_query'
        }
      },
      {
        name: 'lowcode_relationship',
        path: '/lowcode/relationship',
        component: 'view.lowcode_relationship',
        meta: {
          title: 'lowcode_relationship',
          i18nKey: 'route.lowcode_relationship'
        }
      },
      {
        name: 'lowcode_target-project',
        path: '/lowcode/target-project',
        component: 'view.lowcode_target-project',
        meta: {
          title: 'lowcode_target-project',
          i18nKey: 'route.lowcode_target-project'
        }
      },
      {
        name: 'lowcode_template',
        path: '/lowcode/template',
        component: 'view.lowcode_template',
        meta: {
          title: 'lowcode_template',
          i18nKey: 'route.lowcode_template'
        }
      },
      {
        name: 'lowcode_template-manager',
        path: '/lowcode/template-manager',
        component: 'view.lowcode_template-manager',
        meta: {
          title: 'lowcode_template-manager',
          i18nKey: 'route.lowcode_template-manager'
        }
      }
    ]
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage'
    },
    children: [
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu'
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role'
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user'
        }
      },
      {
        name: 'manage_user-detail',
        path: '/manage/user-detail/:id',
        component: 'view.manage_user-detail',
        meta: {
          title: 'manage_user-detail',
          i18nKey: 'route.manage_user-detail'
        }
      }
    ]
  },
  {
    name: 'reload',
    path: '/reload',
    component: 'layout.base$view.reload',
    meta: {
      title: 'reload',
      i18nKey: 'route.reload'
    }
  }
];
